Models/Local.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SupplySearchV1.Models
{
    [Table("LocalEstoque")]
    public class Local
    {
        [Key]
        [Column("ID")]
        public int ID { get; set; }
        [Column("Cpf")]
        public string Cpf { get; set; }
        [Column("RazaoSocial")]
        public string RazaoSocial { get; set; }
        [Column("endereco")]
        public string endereco { get; set; }
        [Column("numero")]
        public int numero { get; set; }
        [Column("complemento")]
        public string? complemento { get; set; }
        [Column("telefone")]
        public string telefone { get; set; }
        [Column("Senha")]
        public string Senha { get; set; }
    }
}

ViewModels/AreaLocalViewModel.cs
using SupplySearchV1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SupplySearchV1.ViewModels
{
    public class AreaLocalViewModel
    {
        public List<Doacoes> Doacoes{ get; set; }
        public Local Local { get; set; }
    }
}

Controllers/DoadorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SupplySearchV1.Models;
using SupplySearchV1.Services;
using SupplySearchV1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SupplySearchV1.Controllers
{
    public class DoadorController : Controller
    {
        private readonly IService _service;
        private readonly ILogger<DoadorController> _logger;
        public DoadorController(ILogger<DoadorController> logger, IService service)
        {
            _service = service;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Logar(Doador doador)
        {
            var usuario = _service.GetDoador();

            var verifica = usuario.Where(x => x.email == doador.email && x.Senha == doador.Senha).FirstOrDefault();

            if (verifica == null)
            {
                return View();
            }

            return RedirectToAction("AreaDoador", verifica);
        }

        public ActionResult AreaDoador(Doador doador)
        {
            var retorno = _service.GetDoacoesByID(doador.ID);

            foreach(var item in retorno)
            {
                item.LocalEntrega = _service.GetLocalByID(item.IDLocal);
            }

            doador.Doacoes = retorno.ToList();

            return View(doador);
        }

        public ActionResult RealizarDoacao(int id)
        {

            var doacaoViewModel = new CadastrarDoacaoViewModel();
            var doador = _service.GetDoadorByID(id);
            var locais = _service.GetLocal();

            doacaoViewModel.Local = locais.ToList();
            doacaoViewModel.Doador = doador;
            return View(doacaoViewModel);
        }
        public ActionResult CadastrarDoacao(Doacoes doacoes)
        {
            _service.CreateDoacoes(doacoes);

            var usuario = _service.GetDoadorByID(doacoes.IDDoador);



            return RedirectToAction("AreaDoador", usuario);
        }



        public ActionResult Cadastro()
        {
            return View();
        }
        public ActionResult Cadastrar(Doador doador)
        {
            if((doador.nome == null)|| (doador.email == null) || (doador.telefone == null) || (doador.Senha == null))
            {
                ViewBag.Erro = "Erro ao criar o doador";
                return View("Cadastro");
            }

            var retorno = _service.CreateDoador(doador);

            return View("Index");
        }




    }
}

Controllers/LocalController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SupplySearchV1.Models;
using SupplySearchV1.Services;
using SupplySearchV1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SupplySearchV1.Controllers
{
    public class LocalController : Controller
    {
        private readonly IService _service;
        private readonly ILogger<LocalController> _logger;
        public LocalController(ILogger<LocalController> logger,IService service)
        {
            _service = service;
        }
        // GET: LocalController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Logar(Local obj)
        {
            var local = _service.GetLocal();

            var verifica = local.Where(x => x.Senha == obj.Senha && x.Cpf == obj.Cpf).FirstOrDefault();

            if (verifica == null)
            {
                return View("Login");
            }

            return RedirectToAction("AreaLocal", verifica);
        }
        public ActionResult Aprovar(int id, int idLocal)
        {
            var local = _service.GetLocalByID(idLocal);

             _service.DeleteDoacao(id);

            return RedirectToAction("AreaLocal", local);
        }
        public ActionResult AreaLocal(Local obj)
        {
            var local = _service.GetLocalByID(obj.ID);
            var doacoes = _service.GetDoacoes().Where(x => x.idDonatario != null).ToList();
            
            foreach (var item in doacoes)
            {
                item.LocalEntrega = _service.GetLocalByID(item.IDLocal);
                item.Donatario = _service.GetDonatarioByID(Convert.ToInt32(item.idDonatario));
            }
            var retorno = new AreaLocalViewModel();
            retorno.Doacoes = doacoes.ToList();
            retorno.Local = local;


            return View(retorno);
        }

        public ActionResult Cadastro()
        {
            return View();
        }
        public ActionResult Cadastrar(Local local)
        {
            if ((local.Cpf == null) || (local.numero == null) || (local.RazaoSocial == null) || (local.Senha == null))
            {
                ViewBag.Erro = "Erro ao criar o doador";
                return View("Cadastro");
            }

            var retorno = _service.CreateLocal(local);

            return View("Index");
        }

    }
}

Views/Local/AreaLocal.cshtml
@using SupplySearchV1.ViewModels 
@model AreaLocalViewModel

<p>
    <h1>Olá, @Model.Local.RazaoSocial</h1>
</p>
<p>
    <h5 style="margin-top:50px">Doações para Aprovar:</h5>

    <table class="table">
        <tr>
            <th>Codigo</th>
            <th>Donatario</th>
            <th>Descrição</th>
            <th>Produto</th>
            <th>Data Entrega</th>
            <th>Quantidade</th>
            <th>Enredeço</th>
            <th>N°</th>
            <th></th>
        </tr>
        @foreach (var item in Model.Doacoes.Where(x => x.IDLocal == Model.Local.ID && x.idDonatario != null).ToList())
        {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.ID)</td>
        <td>@Html.DisplayFor(modelItem => item.Donatario.nome)</td>
        <td>@Html.DisplayFor(modelItem => item.Descricao)</td>
        <td>@Html.DisplayFor(modelItem => item.Produto)</td>
        <td>@Html.DisplayFor(modelItem => item.DiaEntrega)</td>
        <td>@Html.DisplayFor(modelItem => item.Quantidade)</td>
        <td>@Html.DisplayFor(modelItem => item.LocalEntrega.endereco)</td>
        <td>@Html.DisplayFor(modelItem => item.LocalEntrega.numero)</td>
        <td><a href="../Aprovar?id=@item.ID&idLocal=@item.IDLocal" class="btn btn-outline-info">Aprovar</a></td>

    </tr>
        }
    </table>
</p>

Views/Local/Cadastro.cshtml
@model Local
@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastro de Locais</h1>

@if (Model != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

<form asp-action="Cadastrar">
    <div class="form-group">
        <label for="id-Cpf">Cpf</label>
        <input type="text" name="Cpf" class="form-control" id="id-Cpf" />
    </div>
    <div class="form-group">
        <label for="id-RazaoSocial">Razao Social</label>
        <input type="text" name="RazaoSocial" class="form-control" id="id-RazaoSocial" />
    </div>
    <div class="form-group">
        <label for="id-endereco">Endereco</label>
        <input type="text" name="endereco" class="form-control" id="id-endereco" />
    </div>
    <div class="form-group">
        <label for="id-numero">Número</label>
        <input type="text" name="numero" class="form-control" id="id-numero" />
    </div>
    <div class="form-group">
        <label for="id-complemento">Complemento</label>
        <input type="text" name="complemento" class="form-control" id="id-complemento" />
    </div>
    <div class="form-group">
        <label for="id-telefone">Telefone</label>
        <input type="number" name="telefone" class="form-control" id="id-telefone" />
    </div>
    <div class="form-group">
        <label for="id-Senha">Senha</label>
        <input type="text" name="Senha" class="form-control" id="id-Senha" />
    </div>

    <input type="submit" value="Cadastrar" class="btn btn-outline-success" />
    <a asp-controller="Doador" asp-action="index" class="btn btn-outline-primary"> Voltar</a>
</form>

Views/Local/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<p style="margin-top:50px">
    <a class="btn btn-outline-primary"  asp-controller="local" asp-action="login">Já Sou um Local</a>
    <a class="btn btn-primary"  asp-controller="local" asp-action="cadastro">Quero ser um Local</a>
</p>

Views/Local/Login.cshtml
@model Local
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

@if (Model != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

<form asp-action="Logar">
    <div class="form-group">
        <label for="id-Cpf">Cpf</label>
        <input type="text" name="Cpf" class="form-control" id="id-Cpf" />
    </div>
    <div class="form-group">
        <label for="id-Senha">Senha</label>
        <input type="text" name="Senha" class="form-control" id="id-Senha" />
    </div>

    <input type="submit" value="Login" class="btn btn-outline-success" />
    <a asp-controller="Local" asp-action="index" class="btn btn-outline-primary"> Voltar</a>
</form>